neighborhoods = [
['admiral','sw'],
['alki','sw'],
['arbor_heights','sw'],
['atlantic','sw'],
['ballard','nw'],
['beacon_hill','se'],
['belltown', 'nw'],
['bitter_lake', 'nw'],
['blue_ridge', 'nw'],
['brighton','se'],
['broadmoor', 'se'],
['broadview', 'nw'],
['bryant', 'ne'],
['capitol_hill', 'se'],
['cedar_park', 'ne'],
['central_district', 'se'],
['columbia_city', 'se'],
['crown_hill', 'nw'],
['denny', 'se'],
['downtown', 'dt'],
['eastlake', 'se'],
['fauntleroy', 'sw'],
['first_hill', 'se'],
['fremont', 'nw'],
['georgetown', 'se'],
['green_lake', 'nw'],
['greenwood', 'nw'],
['haller_lake', 'nw'],
['hawthorne_hills', 'ne'],
['high_point', 'sw'],
['highland_park', 'se'],
['industrial_district', 'se'],
['interbay', 'nw'],
['international_district', 'se'],
['laurelhurst', 'ne'],
['leschi', 'sw'],
['lower_queen_anne', 'nw'],
['loyal_heights', 'nw'],
['madison_park', 'se'],
['madison_valley', 'se'],
['madrona', 'se'],
['magnolia', 'nw'],
['maple_leaf', 'ne'],
['matthews_beach', 'ne'],
['meadowbrook', 'ne'],
['montlake', 'se'],
['mount_baker','se'],
['north_beach','nw'],
['north_college_park', 'nw'],
['north_delridge', 'sw'],
['northgate', 'ne'],
['olympic_hills', 'ne'],
['olympic_manor', 'nw'],
['phinney_ridge', 'nw'],
['pinehurst', 'ne'],
['pioneer_square', 'se'],
['portage_bay', 'ne'],
['queen_anne', 'nw'],
['rainier_beach', 'se'],
['ravenna', 'ne'],
['riverview', 'sw'],
['roosevelt','ne'],
['roxhill', 'sw'],
['sand_point', 'ne'],
['seward_park', 'se'],
['south_delridge', 'sw'],
['south_lake_union', 'nw'],
['south_park', 'se'],
['sunset_hill', 'nw'],
['university_district', 'ne'],
['victory_heights', 'ne'],
['view_ridge', 'nw'],
['wallingford', 'nw'],
['wedgwood', 'ne'],
['west_seattle', 'sw'],
['westlake', 'nw'],
['whittier_heights','nw'],
['windermere', 'ne']
]